spring:
  datasource:
    # local dev credentials
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: abc123

    initialization-mode: always
    initialize: true
    continue-on-error: true
